---
# vars file for logrotatefix

 team: 'SSMM-MF' 

 logrotateName: 'LOGROTATE-CUSTOM'

 deleteEmptyRotated: true 		#accepted values: false / true
 keepHistoryDays: false			#accepted values: false / [0,1,..]
 keepNumberFiles: 6			#accepted values: false / [0,1,..]

 logrotateOptions:
   - option: 'rotate 1'
   - option: 'compress'
   - option: 'daily'
   - option: 'dateext'
   - option: 'dateformat -%Y-%m-%d.log'
   - option: 'notifempty'

 logs:
   - path:      /var/log/
     filename:  messages
     wildcard:  messages-????????

   - path:	/var/log/
     filename:	boot.log 
     wildcard:	boot.log-????????

   - path:	/var/log/
     filename:	dmesg
     wildcard:	dmesg-????????

   - path:	/var/log/
     filename:	cron
     wildcard:	cron-????????

   - path:	/var/log/
     filename:	maillog
     wildcard:	maillog-????????

   - path:	/var/log/
     filename:	secure
     wildcard:	secure-????????

   - path:	/var/log/
     filename:	spooler
     wildcard:	spooler-????????
 
   - path:	/var/log/httpd/
     filename:	access_log
     wildcard:	access_log-????????
 
   - path:	/var/log/httpd/
     filename:	error_log
     wildcard:	error_log-????????

   - path:	/var/log/
     filename:	btmp
     wildcard:	btmp-????????

   - path:      /var/log/
     filename:  wtmp
     wildcard:  wtmp-????????

   - path:	fakepath
     filename:	fakepath
     wildcard:	fakepath
