---
# tasks file for logrotatefix

  - name: check if logrotate SSMM-MF exists
    copy:
      content: |
             ## CONTENT ADMINISTRATED BY {{ team }} ANSIBLE PLAYBOOK. ALL CHANGES WILL BE LOST
             {
               hourly
               compress
               rotate 90
               dateformat -%Y%m%d-%s
             }
      dest: '/etc/logrotate.d/{{ team }}-{{ logrotateName }}'
      force: no
      group: sys
      owner: root
      mode: 0644
    register: var

  - debug: var=var
  - name: check if log file exists at filesystem
    stat:
      path: "{{ item.path }}"
    with_items: "{{ paths }}"
    register: bootPath

#  - debug: var=item.item['wildcard']
#    with_items: "{{ bootPath.results }}"

  - name: check if .log exists at logrotate SSMM-MF-COMPRESS file
    lineinfile:
      path: "{{ var.dest }}"
      line: "{{ item.item.wildcard }}"
      insertbefore: '^{'
      create: no
    when: item.stat.exists == true
    with_items: "{{ bootPath.results }}"
...
